import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./styles/reset.css";
import "./styles/globals.css";
import "./styles/globals.scss";
import Header from "./components/layouts/Header";
import Footer from "./components/layouts/Footer";

const notoSansJP = Noto_Sans_JP({ subsets: ["latin"], weight: ["300","400","500","700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansJP.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
